In [1]:
import numpy as np
import numpy.polynomial as p

In [6]:
# Coefficients
A = [4, 1, 11, 10]  # Represents 4 + 1x + 11x2 + 10x3
# Secret
sA = [6, 9, 11, 11]  # Represents 6 + 9x + 11x2 + 11x3
# Errors
eA = [0, -1, 1, 1]
# Base Polynomial for division
xN_1 = [1, 0, 0, 0, 1]  # Represents 1 + x^4
# Max value
q = 12

A_new = np.polydiv(A, xN_1)[1] % q
prod1 = np.polymul(A, sA)
prod2 = prod1 % q
prod3 = np.polydiv(prod2, xN_1)[1] % q
final = np.polyadd(prod3, eA) % q

print(f"A_new = {A_new}\nprod1 = {prod1}\nprod2 = {prod2}\nprod3 = {prod3}\nfinal = {final}")

A_new = [ 4.  1. 11. 10.]
prod1 = [ 24  42 119 214 222 231 110]
prod2 = [ 0  6 11 10  6  3  2]
prod3 = [10.  6.  9.  3.]
final = [10.  5. 10.  4.]


# Copy Paste Section

In [5]:
import numpy as np


A = [4,1,11,10]
sA = [6,9,11,11]
eA =[0,-1,1,1]

n=len(A)
q=13

print (A,sA,eA)

xN_1 = [1] + [0] * (n-1) + [1]

print (xN_1)
A = np.floor(np.polydiv(A,xN_1)[1])

bA = np.polymul(A,sA)%q
bA = np.floor(np.polydiv(bA,xN_1)[1])

bA = np.polyadd(bA,eA)%q
bA = np.floor(np.polydiv(bA,xN_1)[1])
print ("Print output\n",bA)

[4, 1, 11, 10] [6, 9, 11, 11] [0, -1, 1, 1]
[1, 0, 0, 0, 1]
Print output
 [6. 2. 8. 5.]


In [9]:
sB = [2, 1, 3, 4]
eB = [1, 0 , -1, 0]

bB = np.polymul(A,sB)%q
bB = np.floor(np.polydiv(sB,xN_1)[1])
bB = np.polyadd(bB,eB)%q

In [11]:
sharedAlice = np.floor(np.polymul(sA,bB)%q)
sharedAlice = np.floor(np.polydiv(sharedAlice,xN_1)[1])%q 
sharedBob = np.floor(np.polymul(sB,bA)%q)
sharedBob = np.floor(np.polydiv(sharedBob,xN_1)[1])%q

In [12]:
sharedAlice

array([2., 3., 9., 2.])

In [13]:
sharedBob

array([1., 1., 8.])