# Slide Example LWE
This notebook covers the example from the slides.

In [1]:
import numpy as np
import secrets

# Check for correct numpy version
np_version = np.version.version
if np_version[:-2] != '1.24':
    print(f"WARNING: NumPy version! Please use NumPy version 1.24.x for the best experience. Use of an incorrect numpy version could cause the printing of polynomials to work differently. As the expected order of polynomial coefficients was changed. In this implementation we expect the order to be highest to lowest degree.")

In [2]:
q = 13
max_error = 1

S = np.array([1, 4, 9])
A_list = np.array([
    [1, 2, 3],
    [7, 4, 8],
    [12, 6, 0]
])  # No of rows can be anything but no of columns must match length of secret
E_list = np.array([1, 0, -1])  # dimensions must match no of rows in As

def calculate_T(As, S, Es, q):
    # Multiply A & S
    T_no_errors = np.matmul(As, S) % q
    T_with_errors = (T_no_errors + Es) % q

    return T_with_errors

T_list = calculate_T(A_list, S, E_list, q)
print(T_list)

[11  4  9]


### Keys

In [3]:
print(f"Public Key:")
print(f"q = {q}\nmax_error = {max_error}\nA_list = {A_list}\nT_list = {T_list}")
print("--------------------------------------------------")
print(f"Private Key:")
print(f"S = {S}")

Public Key:
q = 13
max_error = 1
A_list = [[ 1  2  3]
 [ 7  4  8]
 [12  6  0]]
T_list = [11  4  9]
--------------------------------------------------
Private Key:
S = [1 4 9]


### Encryption

In [4]:
max_equation_weights = 2
A_indexes = [secrets.randbelow(len(A_list)) for _ in range(max_equation_weights)]

A_new = (A_list[A_indexes[0]] + A_list[A_indexes[1]]) % q
T_new = (T_list[A_indexes[0]] + T_list[A_indexes[1]]) % q

Message = 0  # Can only send 1 bit per equation

# Add Message
new_message = Message * (q // 2)
T_send = (T_new + new_message) % q

print(f"Sending:\nT_send = {T_send}\nA_new = {A_new}")

Sending:
T_send = 8
A_new = [1 8 3]


### Decryption

In [5]:
# Find T_ideal
T_ideal = np.matmul(A_new, S) % q

Message_Draft = T_send - T_ideal

final_message = ((Message_Draft + (q//4)) % q) // (q//2)

print(f"Final Message = {final_message}")

Final Message = 0
